name: Pull request status checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read
  actions: read

jobs:
  status-checks:
    name: Run status checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run status checks
        uses: ./.github/actions/status-checks
